#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  formTopic:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Form type identifier.
        required: false
      formType:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Specifies the type code of the form.
        required: false
      question:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Corresponds to the question of the survey
        required: false
