#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  formAnswers: formAnswer.raml

types:
  form:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "NONE"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: |
          Form identifier required for the issue case.
        required: false
      name: 
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "NONE"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          Form name required for the issue case.
        required: false
      formAnswers: 
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: formAnswers.formAnswer[]
        description: |
          Includes the information related to the form identifier, such as question, type of question, answer.
        required: false

