#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  addressComponent : addressComponent.raml

types:
  issueLocation:
    type: object
    properties:
      addressComponents: 
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: addressComponent.addressComponent[]
        description: |
          Additional geographic information.
        required: false