#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  issuer: issuer.raml
  client: client.raml
  area: area.raml
  notes: notes.raml
  parentIssue: parentIssue.raml

types:
  issues:
    type: array
    items:
      properties:
        id:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: string
          description: |
            Issue identifier.
          required: false
        subject:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            Issue subject.
          required: false
        status:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          enum: ["ANSWERED", "APPROVAL_REJECTED", "APPROVED", "CLOSED", "ESCALATED", "LINKED_TO_MASTER_CASE", "NEW", "ON_HOLD", "PENDING_APPROVAL","PENDING_DEVELOPMENT","PENDING_ON_BBVA_TEAM","PENDING_ON_CUSTOMER","PENDING_ON_EXTERNAL_TEAM","PENDING_ON_SUPPLIER","REMEDY_ESCALATED","REMEDY_PENDING_INFORMATION","REMEDY_PENDIENG_TO_CLOSE","REMEDY_REJECTES","REOPEN","TRANSFERRED","WORKING"]
          (annotations.enumDescription):
            - ANSWERED: The case is answered.
            - APPROVAL_REJECTED: The user of Claims rejects the approval of the case.
            - APPROVED: The Claims user approves the case.
            - CLOSED: The case is closed.
            - ESCALATED: The case is scaled to another responsible user.
            - LINKED_TO_MASTER_CASE: Case associated with a master case.
            - NEW: The case has just opened.
            - ON_HOLD: The case remains on hold because it is under study.
            - PENDING_APPROVAL: Case pending approval by Claims user.
            - PENDING_DEVELOPMENT: Salesforce development pending case.
            - PENDING_ON_BBVA_TEAM: Pending case of the BBVA team because they have been sent a notification to BBVA contacts.
            - PENDING_ON_CUSTOMER: Pending case of the client because a notification has been sent to the client.
            - PENDING_ON_EXTERNAL_TEAM: Pending case of an external team because a notification has been sent to an external team.
            - PENDING_ON_SUPPLIER: Case pending from the SERNOVA provider.
            - REMEDY_ESCALATED: Integration status with Remedy.
            - REMEDY_PENDING_INFORMATION: Integration status with Remedy.
            - REMEDY_PENDIENG_TO_CLOSE: Integration status with Remedy.
            - REMEDY_REJECTES: Integration status with Remedy.
            - REOPEN: A closed case that reopens.
            - TRANSFERRED: The case can be transferred to another user or another queue.
            - WORKING: Case under development.
          description: |
            Issue status.
          required: false
        resolution:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            Description of the solution of the incident that the manager has indicated.
          required: false
        issuer:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: issuer.issuer
          description: |
            Information of the petitioner who opens the issue.
          required: false
        appUserId:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            Customer identifier within a financial management company for login purposes. This field is mandatory when the financialManagementCompanyId is neccessary.
          required: false
        financialManagementCompanyId:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            Financial management Company identifier. This field is mandatory when the issue is generated by the system of financial management companies.
          required: false
        description:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: string
          description: |
            Issue description.
          required: false
        sourceSystem:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            System that originates the issue.
          required: false
        origin:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: string
          enum: ["WEB_FORM", "MAX_MISTRAL", "BOSS"]
          (annotations.enumDescription):
            - WEB_FORM: The incidence was generated from a web form.
            - MAX_MISTRAL: The incidence was generated from Max Mistral.
            - BOSS: The incidence was generated from Boss.
          description: |
            Issue origin.
          required: false
        priority:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          enum: ["HIGH","MEDIUM","LOW","UNDEFINED"]
          (annotations.enumDescription):
            - HIGH: The priority of the issue is high.
            - MEDIUM: The priority of the issue is medium.
            - LOW: The priority of the issue is low.
            - UNDEFINED: The priority of the issue is undefined.
          description: |
            Issue priority.
          required: false
        internalIssueId:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            Internal issue identifier in Salesforce.
          required: false
        creationDate:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            String based on ISO 8601 for specifying the creation date of the issue.
          required: false
        classification:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          enum: ["INQUIRY","INCIDENCE","FEEDBACK","ATTENTION","PENDING_ACTIVATION"]
          (annotations.enumDescription):
            - INQUIRY: The issue is considered a query.
            - INCIDENCE: The issue is considered an issue to be resolved.
            - FEEDBACK: The issue is considered as an opinion.
            - ATTENTION: The issue is considered as a request for attention by the issuer.
            - PENDING_ACTIVATION: The issue is considered a request to activate access to a certain system. For example Global Net Cash.
          description: |
            Issue classification.
          required: false
        client:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "OPTIONAL"
              output: "OPTIONAL"
          type: client.client
          description: |
            Max Mistral client.
          required: false
        closeDate:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: datetime
          description: |
            Closing date with format RFC3339.
          required: false
        caseCreator:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            Applies to Max Mistral. It is the user of Max Mistral, the banker.
          required: false
        targetedCompletionDate:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: datetime
          required: false
          description: |
            String based on ISO-8601 date format for specifying the expected close date, based on Service Level Agreement. Date
        action:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          enum: ["NEW","CHANGE","DELETE"]
          (annotations.enumDescription):
            - NEW: New service or product.
            - CHANGE: Change a service or product.
            - DELETE: Delete a service or product.
          description: |
            Type of action performed through the issue.
          required: false
        milestone:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: string
          description: |
            The steps needed to implement, remove or change the product or service.
          required: false
        area:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: area.area
          description: |
            Corresponds to the department responsible for providing solution according to the product that originates the complaint or claim.
          required: false
        notes:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: notes.notes
          description: |
            The list of comments associated with a Case
          required: false
        parentIssue:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "OPTIONAL"
          type: parentIssue.parentIssue
          description: |
            Object that Informs the identifications of the parent issue if the case created is a reply of a previous issue.
          required: false