#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  link:
    type: object
    properties:
      rel:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "NONE"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        (annotations.supportedIn):
          - country: "CO"
        type: string
        description: |
          Relationship between the containing entity and the entity linked to.
        required: false
      href: 
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "NONE"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        (annotations.supportedIn):
          - country: "CO"
        type: string
        description: |
          URI of the entity linked to.
        required: false

