#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  localAmount:
    type: object
    properties:
      amount:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "NONE"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        (annotations.supportedIn):
          - country: "CO"
        type: number
        description: |
          Monetary amount.
        required: false
      currency: 
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "NONE"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        (annotations.supportedIn):
          - country: "CO"
        type: string
        description: |
          String based on ISO-4217 for specifying the currency related to the monetary amount.
        required: false

