#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  preservationInfo:
    type: object
    properties:
      preservationDate:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: datetime
        description: |
          Creation date plus Legal period of retention documentary.
        required: false
      physicalPreservationDate:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: datetime
        description: |
          Creation date plus Legal period of retention documentary for physical documentation.
        required: false
      signature:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          Tracking number that makes reference to the physical location of the original document.
        required: false