#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  securityLevelInfo:
    type: object
    properties:
      confidentiality:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: |
          This is the metadata for confidentiality treatment to apply (eg. VIP/Senior Management, Political exposed people (PEP)...).
        required: false
      securityLevel:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          Data of Security to access to the document, defined by every country. For this field, allowed values are from 1 to 10.
        required: false
      classificationLevel:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          Data of Security to access to the document, defined by the company. For this field, allowed values are from 1 to 10.
        required: false