#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  subarea:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Subarea identifier. Descriptor of specific service provided or product affected.
        required: false