#%RAML 1.0 Library
uses:
  annotations:  ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
types:
  attachmentsTopic:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Attachment identifier
        required: false
      name:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Document name
        required: false
      