#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  questionType: questionType.raml
types:
  formAnswer:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: |
          Form Identifier.
        required: false
      questionId:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: |
          Identifier of the question.
        required: false
      question:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: |
          Statement of the question.
        required: false
      questionType:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: questionType.questionType
        description: |
          Type of response to give for this question.
        required: false
      answer:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          Client answer to the corresponding question.
        required: false
      isRequired:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: boolean
        description: |
          Indicator that if the question is required or not to answer.
        required: false