#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  documentTypeCategorization: documentTypeCategorization.raml

types:
  categorization:
    type: object
    properties:
      documentType:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: documentTypeCategorization.documentTypeCategorization
        description: |
          Document type identifier and its taxonomy.
        required: false