#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  issuer: issuer.raml
  client: client.raml
  area: area.raml
  notes: notes.raml
  form: form.raml
  attachment: attachment.raml
  contract: contract.raml
  parentIssue: parentIssue.raml
  nonCustomer: nonCustomer.raml
  customer: customer.raml
  issueLocation: issueLocation.raml

types:
  issue:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Issue identifier.
        required: false
      subject:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        (annotations.supportedIn):
          - country: "CO"
        type: string
        description: |
          Issue subject.
        required: false
      resolution:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "NONE"
        type: string
        description: |
          Description of the solution of the incident that the manager has indicated.
        required: false
      targetUserId:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "NONE"
        type: string
        description: |
          Customer identifier for channel control purposes: channel + internal bank + reference + user".
        required: false
      appUserId:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          Customer identifier within a financial management company for login purposes. This field is mandatory when the financialManagementCompanyId is neccessary.
        required: false
      financialManagementCompanyId:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "NONE"
        (annotations.supportedIn):
          - country: "CO"
        type: string
        description: |
          Financial management Company identifier. This field is mandatory when the issue is generated by the system of financial management companies.
        required: false
      description:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        (annotations.supportedIn):
          - country: "CO"
        type: string
        description: |
          Issue description.
        required: false
      sourceSystem:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          System that originates the issue.
        required: false
      sourceSystemCode:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        (annotations.supportedIn):
          - country: "CO"
            method: "POST"
        type: string
        description: |
          Chanel id across to complain regarding with the coding published by the Supervisory Institution.
        required: false
      internalIssueId:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Internal issue identifier in Salesforce.
        required: false
      creationDate:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: string
        description: |
          String based on ISO 8601 for specifying the creation date of the issue.
        required: false
      closeDate:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: datetime
        description: |
          Closing date with format RFC3339.
        required: false
      caseCreator:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          Applies to Max Mistral. It is the user of Max Mistral, the banker.
        required: false
      targetedCompletionDate:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: datetime
        description: |
          String based on ISO-8601 date format for specifying the expected close date, based on Service Level Agreement. Date
        required: false
      origin:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        (annotations.supportedIn):
          - country: "CO"
        type: string
        enum: ["WEB_FORM", "MAX_MISTRAL", "BOSS"]
        (annotations.enumDescription):
          - WEB_FORM: The incidence was generated from a web form.
          - MAX_MISTRAL: The incidence was generated from Max Mistral.
          - BOSS: The incidence was generated from Boss.
        description: |
          Issue origin.
        required: false
      priority:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: string
        enum: ["HIGH","MEDIUM","LOW","UNDEFINED"]
        (annotations.enumDescription):
          - HIGH: The priority of the issue is high.
          - MEDIUM: The priority of the issue is medium.
          - LOW: The priority of the issue is low.
          - UNDEFINED: The priority of the issue is undefined.
        description: |
          Issue priority.
        required: false
      milestone:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: string
        description: |
          The steps needed to implement, remove or change the product or service.
        required: false
      specificSubject:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "NONE"
        type: string
        description: |
          Specific issue subject of the case, that the customer report.
        required: false
      classification:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        (annotations.supportedIn):
          - country: "CO"
        type: string
        enum: ["INQUIRY","INCIDENCE","FEEDBACK","ATTENTION","PENDING_ACTIVATION"]
        (annotations.enumDescription):
          - INQUIRY: The issue is considered a query.
          - INCIDENCE: The issue is considered an issue to be resolved.
          - FEEDBACK: The issue is considered as an opinion.
          - ATTENTION: The issue is considered as a request for attention by the issuer.
          - PENDING_ACTIVATION: The issue is considered a request to activate access to a certain system. For example Global Net Cash.
        description: |
          Issue classification.
        required: false
      status:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "NONE"
        type: string
        enum: ["ANSWERED", "APPROVAL_REJECTED", "APPROVED", "CLOSED", "ESCALATED", "LINKED_TO_MASTER_CASE", "NEW", "ON_HOLD", "PENDING_APPROVAL","PENDING_DEVELOPMENT","PENDING_ON_BBVA_TEAM","PENDING_ON_CUSTOMER","PENDING_ON_EXTERNAL_TEAM","PENDING_ON_SUPPLIER","REMEDY_ESCALATED","REMEDY_PENDING_INFORMATION","REMEDY_PENDIENG_TO_CLOSE","REMEDY_REJECTES","REOPEN","TRANSFERRED","WORKING","CANCELLED"]
        (annotations.enumDescription):
          - ANSWERED: The case is answered.
          - APPROVAL_REJECTED: The user of Claims rejects the approval of the case.
          - APPROVED: The Claims user approves the case.
          - CLOSED: The case is closed.
          - ESCALATED: The case is scaled to another responsible user.
          - LINKED_TO_MASTER_CASE: Case associated with a master case.
          - NEW: The case has just opened.
          - ON_HOLD: The case remains on hold because it is under study.
          - PENDING_APPROVAL: Case pending approval by Claims user.
          - PENDING_DEVELOPMENT: Salesforce development pending case.
          - PENDING_ON_BBVA_TEAM: Pending case of the BBVA team because they have been sent a notification to BBVA contacts.
          - PENDING_ON_CUSTOMER: Pending case of the client because a notification has been sent to the client.
          - PENDING_ON_EXTERNAL_TEAM: Pending case of an external team because a notification has been sent to an external team.
          - PENDING_ON_SUPPLIER: Case pending from the SERNOVA provider.
          - REMEDY_ESCALATED: Integration status with Remedy.
          - REMEDY_PENDING_INFORMATION: Integration status with Remedy.
          - REMEDY_PENDIENG_TO_CLOSE: Integration status with Remedy.
          - REMEDY_REJECTES: Integration status with Remedy.
          - REOPEN: A closed case that reopens.
          - TRANSFERRED: The case can be transferred to another user or another queue.
          - WORKING: Case under development.
          - CANCELLED: The case is cancelled.
        description: |
          Issue status.
        required: false
      action:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: string
        enum: ["NEW","CHANGE","DELETE"]
        (annotations.enumDescription):
          - NEW: New service or product.
          - CHANGE: Change a service or product.
          - DELETE: Delete a service or product.
        description: |
          Type of action performed through the issue.
        required: false
      notes:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: notes.notes
        description: |
          The list of comments associated with a Case
        required: false
      location:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: issueLocation.issueLocation
        description: |
          Physical location address where the event occurred.
        required: false
      client:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: client.client
        description: |
          Max Mistral client.
        required: false
      form:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "NONE"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: form.form
        description: |
          Required form for the specific case.
        required: false
      area:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: area.area
        description: |
          Identifies what service is being provided and what product is affected.
        required: false
      attachments:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "NONE"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: attachment.attachment[]
        description: |
          Required if the client has any attachments
        required: false
      issuer:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: issuer.issuer
        description: |
          Information of the petitioner who opens the issue.
        required: false
      contract:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "NONE"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: contract.contract
        description: |
          Financial product. This is the commercial name by which the user knows this product.
        required: false
      remainingAttachmentDays:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
        type: number
        description: |
          Specifies the missing days that the issuer has to attach all the required documents, if the client does not attach all the required documents on the dates stipulated by Salesforce the case is automatically closed.
        required: false
      ocurrenceDate:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        (annotations.supportedIn):
          - country: "CO"
        type: date-only
        description: |
          Day on which the occurrence reported by the client occurs.
        required: false
      reviewProcessStartDate:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
        type: datetime
        description: |
          Specify the date which the issue goes into review on Salesforce.
        required: false
      parentIssue:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: parentIssue.parentIssue
        description: |
          Object that Informs the identifications of the parent issue if the case created is a reply of a previous issue.
        required: false
      replyTopic:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: |
          Informs the topic of a issue, that a customer reports when it has an specific request from a previous issue attended by Salesforce.
        required: false
      claimant:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: nonCustomer.nonCustomer | customer.customer
        description: |
          Identity document information related to the claimant, after making a previous verification if the claimant is a customer or non customer from the bank.
        required: false