#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  addressComponent : addressComponent.raml

types:
  location:
    type: object
    properties:
      formattedAddress:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: |
          Complete address of the location. This value will be masked when basic authentication state. If the authentication state is advanced the value will be clear.
        required: true
      addressComponents: 
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: addressComponent.addressComponent[]
        description: |
          Additional geographic information.
        required: false

